# Generated by Django 5.2.1 on 2025-05-24 14:11

import colorfield.fields
import django.core.files.storage
import django.db.models.deletion
import main.models
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main', '0001_initial'), ('main', '0002_remove_appversion_yanked'), ('main', '0003_appversion_file_size_alter_appscreenshot_app_and_more'), ('main', '0004_appversion_description'), ('main', '0005_alter_appversionprivacy_unique_together_and_more'), ('main', '0006_alter_app_icon_alter_appscreenshot_image_and_more'), ('main', '0007_sourceapp_featured'), ('main', '0008_remove_news_app_news_source'), ('main', '0009_news_public'), ('main', '0010_news_app')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('bundle_id', models.CharField(db_index=True, max_length=255, null=True, unique=True)),
                ('apple_app_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('developer_name', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8002/sources', location=pathlib.PurePosixPath('/Users/q/Documents/source-pilot/sources')), upload_to=main.models.rename_file_icons)),
                ('tint_colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('category', models.CharField(choices=[('developer', 'Developer Utilities'), ('entertainment', 'Entertainment'), ('games', 'Games'), ('lifestyle', 'Lifestyle'), ('other', 'Other'), ('photo-video', 'Photo & Video'), ('social', 'Social Networking'), ('utilities', 'Utilities')], default='other', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8002/sources', location=pathlib.PurePosixPath('/Users/q/Documents/source-pilot/sources')), upload_to=main.models.rename_file_icons)),
                ('header', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8002/sources', location=pathlib.PurePosixPath('/Users/q/Documents/source-pilot/sources')), upload_to=main.models.rename_file_headers)),
                ('website', models.URLField(blank=True, null=True)),
                ('tint_colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bundle_version_short_string', models.CharField(max_length=255)),
                ('bundle_version', models.CharField(max_length=255)),
                ('marketing_version', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('minimum_os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('maximum_os_version', models.CharField(blank=True, max_length=255, null=True)),
                ('public', models.BooleanField(blank=True, default=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='main.app')),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('date', models.DateTimeField()),
                ('tint_colour', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8002/sources', location=pathlib.PurePosixPath('/Users/q/Documents/source-pilot/sources')), upload_to=main.models.rename_file_news)),
                ('notify', models.BooleanField(blank=True, default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='main.source')),
                ('public', models.BooleanField(blank=True, default=False)),
                ('app', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='main.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppScreenshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='http://localhost:8002/sources', location=pathlib.PurePosixPath('/Users/q/Documents/source-pilot/sources')), upload_to=main.models.rename_file_screenshots)),
                ('iphone', models.BooleanField(blank=True, default=True)),
                ('ipad', models.BooleanField(blank=True, default=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='main.app')),
            ],
        ),
        migrations.CreateModel(
            name='AppEntitlements',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entitlement', models.CharField(max_length=255)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='main.app')),
            ],
            options={
                'unique_together': {('app', 'entitlement')},
            },
        ),
        migrations.CreateModel(
            name='AppPrivacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('privacy_key', models.CharField(max_length=255)),
                ('usage_description', models.TextField()),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy', to='main.app')),
            ],
            options={
                'unique_together': {('app', 'privacy_key')},
            },
        ),
        migrations.CreateModel(
            name='SourceApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='main.app')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to='main.source')),
                ('featured', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
